version: '3.8'

services:
  database:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: mysql
  backend:
    container_name: delivery
    build: .
    restart: 'always'
    ports:
      - 3001:3001
    command: npm run dev
    depends_on:
      - database

volumes:
  pgdata:
    driver: local